#+title: business
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+description: The Compiler Company Business Model
#+setupfile: ../clean.theme
Our objective is to infiltrate markets, apply our methodology, and
develop competitive domain-specific solutions. 

Our solutions respect users. We do not create black boxes. We protect
user privacy and freedom no matter the cost. 

Our software is different. So are we, and so are our customers. We do
not design software for casual users, we design software for *power
users*. When you use choose to use our software you are choosing to
reject consumerist technology as much as humanly possible in a modern
research environment. You are setting yourself up to never be at the
mercy of a malicious tech company who create products first and
software second. No matter the solutions (applications) we offer, we
aim to provide a blueprint for establishing your own unique and
extremely specialized environment using our tools and discovering the
joy of complete software freedom.

Our software puts you in the driver's seat and encourages you to take
a peek under the hood to suit your specific needs because *that's
what it takes to be the best at what you do*.

We build businesses and programmatic revenue streams the exact same
way we build software. Our businesses are effectively programs
operated remotely using our software.
